SEL01 SELECT P.ID, \
             P.NAME, \
             P.PRICE \
        FROM PRODUCT P \
       ORDER BY P.ID
       
SEL02 SELECT P.ID, \
             P.NAME, \
             P.PRICE \
        FROM PRODUCT P \
       WHERE P.NAME LIKE ? \
       ORDER BY P.ID

SEL03 SELECT P.NAME \
        FROM PRODUCT P \
       WHERE P.NAME = ?

SEL04 SELECT P.ID, \
             P.NAME, \
             P.PRICE \
        FROM PRODUCT P \
       WHERE P.PRICE <= ? \
       ORDER BY P.ID

EXS01 SELECT EXISTS (SELECT 1 \
                       FROM PRODUCT P \
                      WHERE P.NAME = ?) DUP

INS01 INSERT INTO PRODUCT \
        (NAME, PRICE) \
      VALUES \
        (?, ?)